"""add unique constraint claim identity

Revision ID: 09fbfe4384ed
Revises: f0301cb22f83
Create Date: 2026-01-04 11:07:01.305867

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09fbfe4384ed'
down_revision: str | Sequence[str] | None = 'f0301cb22f83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_claim_state_county_case', 'surplus_claims', ['state', 'county', 'case_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_claim_state_county_case', 'surplus_claims', type_='unique')
    # ### end Alembic commands ###
