"""add soft delete to surplus_claims

Revision ID: 3de2ccae4dd7
Revises: b24d859daa9c
Create Date: 2026-01-06 07:01:14.786806

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3de2ccae4dd7'
down_revision: str | Sequence[str] | None = 'b24d859daa9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('surplus_claims', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surplus_claims', 'deleted_at')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    # ### end Alembic commands ###
