"""create surplus_claims

Revision ID: f0301cb22f83
Revises: 
Create Date: 2026-01-04 09:14:58.449157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0301cb22f83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surplus_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=120), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('property_address', sa.String(length=255), nullable=False),
    sa.Column('surplus_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surplus_claims_case_number'), 'surplus_claims', ['case_number'], unique=False)
    op.create_index(op.f('ix_surplus_claims_county'), 'surplus_claims', ['county'], unique=False)
    op.create_index(op.f('ix_surplus_claims_state'), 'surplus_claims', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surplus_claims_state'), table_name='surplus_claims')
    op.drop_index(op.f('ix_surplus_claims_county'), table_name='surplus_claims')
    op.drop_index(op.f('ix_surplus_claims_case_number'), table_name='surplus_claims')
    op.drop_table('surplus_claims')
    # ### end Alembic commands ###
